=== dnr/styx/cmd/spin/Pins.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/dnr/styx/main/cmd/spin/Pins.schema.json",
  "title": "Spin pins",
  "description": "A Pins.json file generated by Spin.",
  "type": "object",
  "additionalProperties": false,
  "required": ["$doc", "$schema", "$storeDir", "$version", "pins"],
  "properties": {
    "$doc": {
      "type": "string"
    },
    "$schema": {
      "type": "string",
      "format": "uri"
    },
    "$storeDir": {
      "type": "string",
      "minLength": 1
    },
    "$version": {
      "const": "spin-1"
    },
    "pins": {
      "description": "Null in a newly initialized file, otherwise an array of pins.",
      "type": ["array", "null"],
      "items": {
        "$ref": "#/$defs/pin"
      }
    }
  },
  "$defs": {
    "pin": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "name",
        "storePathName",
        "storePathHash",
        "outputHash",
        "originalUrl",
        "resolvedUrl"
      ],
      "properties": {
        "name": {
          "type": "string",
          "minLength": 1
        },
        "storePathName": {
          "type": "string",
          "minLength": 1
        },
        "storePathHash": {
          "type": "string",
          "pattern": "^[0-9abcdfghijklmnpqrsvwxyz]{32}$"
        },
        "outputHash": {
          "type": "string",
          "pattern": "^sha256:[0-9a-f]{64}$"
        },
        "originalUrl": {
          "type": "string",
          "format": "uri"
        },
        "resolvedUrl": {
          "type": "string",
          "format": "uri"
        }
      }
    }
  }
}

=== dnr/styx/Pins.json
{
  "$doc": "This file contains Nix pins using the 'spin' styx-based pinning tool. See https://github.com/dnr/styx/tree/main/cmd/spin",
  "$schema": "https://raw.githubusercontent.com/dnr/styx/main/cmd/spin/Pins.schema.json",
  "$storeDir": "/nix/store",
  "$version": "spin-1",
  "pins": [
    {
      "name": "nixpkgs",
      "storePathName": "nixexprs-nixos-26.05.8538",
      "storePathHash": "1kp0hi6s4w44l80vf2jgz5q8wdjcmjzm",
      "outputHash": "sha256:a5b9bc06b9ad23894e5eddacc89dc53f5d8b8f26d8ba24dd50ed0642b6d0324d",
      "originalUrl": "https://channels.nixos.org/nixos-26.05/nixexprs.tar.xz",
      "resolvedUrl": "https://releases.nixos.org/nixos/26.05/nixos-26.05.8538.d57af924f160/nixexprs.tar.xz"
    },
    {
      "name": "nix-gocacheprog",
      "storePathName": "github-dnr-nix-gocacheprog",
      "storePathHash": "yx39amlm0s2xi6srdfazsl04cf3gnxfj",
      "outputHash": "sha256:4e055682ea2d2449893735340f686dbd8c3e68d713104d8d47d563c1689e4db0",
      "originalUrl": "https://github.com/dnr/nix-gocacheprog/archive/main.tar.gz",
      "resolvedUrl": "https://github.com/dnr/nix-gocacheprog/archive/349d679ae5471b2857f229e8e4530cd0c6415eb4.tar.gz"
    }
  ]
}
